In [1]:
import jax
import jax.numpy as jnp
import numpy as np
import matplotlib.pyplot as plt
import os
import time

os.environ["KERAS_BACKEND"] = "jax"

import keras

from Laplace_JAXDense import solve_and_loss, solve

# Set the random seed
np.random.seed(1234)
keras.utils.set_random_seed(1234)

dtype='float64' # double precision set to default in the SCR functions
jax.config.update("jax_enable_x64", True)
keras.backend.set_floatx(dtype)

from NN_model import make_model, make_loss_model

In [2]:
model  = make_model(10, 3, 5)
sigmas = jnp.array([0.5, 1, 2, 4], dtype = dtype)
thetas = model(sigmas)

jax.vmap(solve_and_loss)(thetas[:,None])


Array([-0.54860593, -0.55269547, -0.55519627, -0.55436982], dtype=float64)

In [3]:
loss = make_loss_model(model, solve_and_loss, sigmas)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step


AttributeError: Exception encountered when calling loss.call().

'str' object has no attribute '_error_repr'

Arguments received by loss.call():
  • args=('<KerasTensor shape=(None, 1), dtype=float64, sparse=False, name=x_input>',)
  • kwargs=<class 'inspect._empty'>

In [16]:
loss = make_loss_model(model, solve_and_loss, sigmas)

loss(jnp.array([1]))

Array(-2.16229115, dtype=float64)

In [22]:
model(sigmas[:,None])

Array([[ 0.03157711],
       [ 0.04159576],
       [-0.02823659],
       [-0.30107659]], dtype=float64)

In [ ]:
thetas = model(sigmas)
jax.vmap(solve)(thetas[:, None])

(Array([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float64),
 Array([[0.        , 0.98013107],
        [0.        , 0.98013107],
        [0.        , 0.98013107],
        [0.        , 0.98013107]], dtype=float64))

In [53]:
model = make_model(5)
init_nodes = model(jnp.array([1]))
theta_1 = jnp.array([[0.1, 0.2, 0.5, 0.2]])
theta_2 = jnp.array([[0.25, 0.25, 0.25, 0.25]])

thetas = jnp.array([theta_1, theta_2])
thetas

Array([[[0.1 , 0.2 , 0.5 , 0.2 ]],

       [[0.25, 0.25, 0.25, 0.25]]], dtype=float64)

In [54]:
jax.vmap(solve)(thetas)

(Array([[0.        , 0.21266793, 0.44770233, 0.76496559, 1.        ],
        [0.        , 0.25      , 0.5       , 0.75      , 1.        ]],      dtype=float64),
 Array([[0.        , 0.33149079, 0.5629766 , 0.82224691, 0.9932589 ],
        [0.        , 0.37128653, 0.60801778, 0.81006002, 0.99245915]],      dtype=float64))

In [46]:
jax.vmap(solve)(thetas)


IndexError: tuple index out of range